---
title: "Demonstrating the ESD test"
author: "Xavier Didelot"
date: '`r Sys.Date()`'
output:
  pdf_document: default
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Demonstrating the ESD test}
  %\usepackage[utf8]{inputenc}
---

In this vignette we demonstrate the use of the g-esd test.

```{r}
library(DetectImports)
library(ape)
set.seed(0)
```

# Simulation with no imports and constant pop size

```{r}
Ne=function(t){return(0.5)}
tree=simCoal(seq(2020,2021,0.001),Ne)
plot(tree,show.tip.label = F)
axisPhylo(backward = F)
```

```{r}
res=detectImportsESD(tree,showPlot=T)
```


# Simulation with a single import

Let's consider that the local population started in 2020 and a single import occurred in 2020.5.
1000 genomes were sampled between 2020 and 2021.

```{r}
set.seed(1)
tree=simImports(localPopStart=2020,importDates=c(2020.5),
                samplingStartDate=2020,samplingEndDate=2021,samplingNumber=1000)
plot(tree,show.tip.label = F)
axisPhylo(backward = F)
```

```{r}
res=detectImportsESD(tree,showPlot=T)
```

