#Test all is running without error
context("Test running without error")

test_that("Basic functions are running without error.", {
  set.seed(0)
  expect_silent(tree<-simCoal(seq(2000,2020,0.1),function(t){return(5)}))
  expect_is(tree,'phylo')
  expect_silent(res<-detectImportsFAST(tree,constant=T))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(res<-detectImportsFAST(tree))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(res<-detectImportsFAST(tree,online=T))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(res<-detectImportsESD(tree))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(res<-detectImports(tree,constant=T,verbose=F,iter=100,nchains=1))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(res<-detectImports(tree,constant=F,verbose=F,iter=100,nchains=1))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
})
