#Test all is running without error
context("Test running without error")

test_that("Basic functions are running without error.", {
  set.seed(0)
  expect_silent(tree<-simCoal(seq(2000,2020,0.1),function(t){return(5)}))
  expect_is(tree,'phylo')
  expect_silent(suppressMessages(res<-test0(tree)))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(suppressMessages(res<-test1(tree)))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(suppressMessages(res<-test1(tree,online=T)))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
  expect_silent(suppressMessages(res<-test2(tree)))
  expect_is(res,'resDetectImports')
  expect_gt(min(res$pvals,na.rm = T),0.05)
})
